I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 8, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio._portaudio'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    init python:
  File "/Users/jamie/Programming/renpy-8.1.0-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/jamie/Programming/renpy-8.1.0-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 8, in <module>
    import pyaudio
  File "/Users/jamie/Programming/renpy-8.1.0-sdk/renpy/loader.py", line 1020, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/pyaudio/__init__.py", line 111, in <module>
ModuleNotFoundError: No module named 'pyaudio._portaudio'

macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.0.23050201
SexII 1.0
Fri May  5 19:20:14 2023
